services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=aNOOBis24
      - POSTGRES_PASSWORD=SomeWordsandNumber2
      - POSTGRES_DB=scrapper
    volumes:
      - link-service-data:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=aNOOBis24
      - --password=SomeWordsandNumber2
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

volumes:
  link-service-data:

networks:
  backend:
    name: backend